apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: web-rs-selector
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
          - apache

  template:
    metadata:
      labels:
        app: nginx

    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 8080

        - name: apache
          image: httpd
          ports:
            - containerPort: 80